using Eidolon.Core.Domain;

namespace Eidolon.App.Localization
{
    public static class StudioMessageTemplates
    {
        public static string GetName(StudioMessageCode code)
        {
            switch (code)
            {
                case StudioMessageCode.InvalidTrainingBackground:
                    return "EidolonText430";
                case StudioMessageCode.TrainingImageProcessingFailed:
                    return "EidolonText431";
                case StudioMessageCode.InvalidGenerationSeed:
                    return "EidolonText421";
                case StudioMessageCode.InvalidTrainingSteps:
                    return "EidolonText338";
                case StudioMessageCode.BackgroundModelDownloading:
                    return "EidolonText310";
                case StudioMessageCode.BackgroundRemoving:
                    return "EidolonText311";
                case StudioMessageCode.BackgroundRemoved:
                    return "EidolonText312";
                case StudioMessageCode.InvalidGenerationRecord:
                    return "EidolonText313";
                case StudioMessageCode.GenerationRecordBusy:
                    return "EidolonText314";
                case StudioMessageCode.BackgroundRemovalFailed:
                    return "EidolonText315";
                case StudioMessageCode.BackgroundSubjectNotFound:
                    return "EidolonText482";
                case StudioMessageCode.InvalidGenerationDirectory:
                    return "EidolonText300";
                case StudioMessageCode.DownloadingOutlineNodes:
                    return "EidolonText287";
                case StudioMessageCode.InstallingOutlineDependencies:
                    return "EidolonText288";
                case StudioMessageCode.CustomNodeFileMissing:
                    return "EidolonText289";
                case StudioMessageCode.InvalidComfyServer:
                    return "EidolonText270";
                case StudioMessageCode.PromptRequired:
                    return "EidolonText001";
                case StudioMessageCode.LoraRequired:
                    return "EidolonText002";
                case StudioMessageCode.ModelFamilyMismatch:
                    return "EidolonText003";
                case StudioMessageCode.GenerationCompleted:
                    return "EidolonText004";
                case StudioMessageCode.DatasetRequired:
                    return "EidolonText005";
                case StudioMessageCode.LoraNameRequired:
                    return "EidolonText006";
                case StudioMessageCode.TriggerRequired:
                    return "EidolonText007";
                case StudioMessageCode.InvalidTrigger:
                    return "EidolonText008";
                case StudioMessageCode.ReleasingEngineMemory:
                    return "EidolonText009";
                case StudioMessageCode.RegisteringTrainedLora:
                    return "EidolonText010";
                case StudioMessageCode.LoraRegistrationFailed:
                    return "EidolonText011";
                case StudioMessageCode.TrainingCompleted:
                    return "EidolonText012";
                case StudioMessageCode.ModelRequired:
                    return "EidolonText013";
                case StudioMessageCode.CheckpointRequired:
                    return "EidolonText014";
                case StudioMessageCode.ModelFamilyRequired:
                    return "EidolonText015";
                case StudioMessageCode.AssetSourceMismatch:
                    return "EidolonText016";
                case StudioMessageCode.ModelFileMissing:
                    return "EidolonText017";
                case StudioMessageCode.JobCancelled:
                    return "EidolonText018";
                case StudioMessageCode.InvalidEnginePort:
                    return "EidolonText021";
                case StudioMessageCode.AbsoluteInstallPathRequired:
                    return "EidolonText022";
                case StudioMessageCode.InvalidGenerationSettings:
                    return "EidolonText023";
                case StudioMessageCode.UnsupportedGenerationFamily:
                    return "EidolonText024";
                case StudioMessageCode.SafetensorsRequired:
                    return "EidolonText025";
                case StudioMessageCode.WeightsFamilyMismatch:
                    return "EidolonText026";
                case StudioMessageCode.InspectingModel:
                    return "EidolonText027";
                case StudioMessageCode.AssetFamilyRequired:
                    return "EidolonText028";
                case StudioMessageCode.InvalidAssetFamily:
                    return "EidolonText029";
                case StudioMessageCode.UnsupportedAssetSchema:
                    return "EidolonText030";
                case StudioMessageCode.InvalidAssetCatalog:
                    return "EidolonText031";
                case StudioMessageCode.EnginePortOccupied:
                    return "EidolonText032";
                case StudioMessageCode.EngineStarting:
                    return "EidolonText033";
                case StudioMessageCode.EngineExitedDuringStartup:
                    return "EidolonText034";
                case StudioMessageCode.EngineReady:
                    return "EidolonText035";
                case StudioMessageCode.EngineStartupTimedOut:
                    return "EidolonText036";
                case StudioMessageCode.ProgressConnectionUnavailable:
                    return "EidolonText037";
                case StudioMessageCode.GenerationQueued:
                    return "EidolonText038";
                case StudioMessageCode.GenerationFailed:
                    return "EidolonText039";
                case StudioMessageCode.GenerationOutputMissing:
                    return "EidolonText040";
                case StudioMessageCode.GenerationTimedOut:
                    return "EidolonText041";
                case StudioMessageCode.EngineCancellationFailed:
                    return "EidolonText042";
                case StudioMessageCode.ProgressMessageTooLarge:
                    return "EidolonText044";
                case StudioMessageCode.GenerationProgress:
                    return "EidolonText045";
                case StudioMessageCode.ProcessingModel:
                    return "EidolonText046";
                case StudioMessageCode.EngineRequestFailed:
                    return "EidolonText047";
                case StudioMessageCode.IncompleteDownload:
                    return "EidolonText048";
                case StudioMessageCode.InvalidDownloadRange:
                    return "EidolonText049";
                case StudioMessageCode.DownloadProgress:
                    return "EidolonText050";
                case StudioMessageCode.DownloadInterrupted:
                    return "EidolonText051";
                case StudioMessageCode.VerifyingDownload:
                    return "EidolonText052";
                case StudioMessageCode.DownloadChecksumMismatch:
                    return "EidolonText053";
                case StudioMessageCode.TrainingGpuRequired:
                    return "EidolonText054";
                case StudioMessageCode.TrainingModelMissing:
                    return "EidolonText055";
                case StudioMessageCode.TrainingImagesMissing:
                    return "EidolonText056";
                case StudioMessageCode.PreparingDataset:
                    return "EidolonText057";
                case StudioMessageCode.CheckingTrainingEnvironment:
                    return "EidolonText058";
                case StudioMessageCode.TrainingStarting:
                    return "EidolonText059";
                case StudioMessageCode.TrainingProgress:
                    return "EidolonText060";
                case StudioMessageCode.TrainingRunning:
                    return "EidolonText061";
                case StudioMessageCode.TrainingOutputMissing:
                    return "EidolonText062";
                case StudioMessageCode.ProcessStartFailed:
                    return "EidolonText063";
                case StudioMessageCode.ProcessFailed:
                    return "EidolonText064";
                case StudioMessageCode.UnsupportedInstallationPlatform:
                    return "EidolonText065";
                case StudioMessageCode.InstallationDirectoryOccupied:
                    return "EidolonText066";
                case StudioMessageCode.InvalidInstallationOwner:
                    return "EidolonText067";
                case StudioMessageCode.DownloadingInstaller:
                    return "EidolonText068";
                case StudioMessageCode.InstallingPython:
                    return "EidolonText069";
                case StudioMessageCode.DownloadingEngines:
                    return "EidolonText070";
                case StudioMessageCode.PreparingPythonEnvironments:
                    return "EidolonText071";
                case StudioMessageCode.InstallingDependencies:
                    return "EidolonText072";
                case StudioMessageCode.ConnectingModelDirectories:
                    return "EidolonText073";
                case StudioMessageCode.InstallationCompleted:
                    return "EidolonText074";
                case StudioMessageCode.ArchiveTooLarge:
                    return "EidolonText075";
                case StudioMessageCode.ArchiveLinkUnsupported:
                    return "EidolonText076";
                case StudioMessageCode.ArchivePathInvalid:
                    return "EidolonText077";
                case StudioMessageCode.InstallDirectoryRequired:
                    return "EidolonText078";
                case StudioMessageCode.InstallPathInvalid:
                    return "EidolonText079";
                case StudioMessageCode.AssetPathInvalid:
                    return "EidolonText080";
                case StudioMessageCode.UnsupportedRuntimePlatform:
                    return "EidolonText081";
                case StudioMessageCode.RuntimeNotInstalled:
                    return "EidolonText082";
                case StudioMessageCode.RuntimeIncomplete:
                    return "EidolonText083";
                case StudioMessageCode.UnsupportedRuntimeSchema:
                    return "EidolonText084";
                case StudioMessageCode.RuntimeVersionMismatch:
                    return "EidolonText085";
                case StudioMessageCode.GenerationRuntimeMissing:
                    return "EidolonText086";
                case StudioMessageCode.TrainingRuntimeMissing:
                    return "EidolonText087";
                case StudioMessageCode.InvalidSafetensorsHeader:
                    return "EidolonText088";
                case StudioMessageCode.IncompleteSafetensors:
                    return "EidolonText089";
                case StudioMessageCode.InvalidTensorRange:
                    return "EidolonText090";
                case StudioMessageCode.UnsupportedAssetArchitecture:
                    return "EidolonText091";
                case StudioMessageCode.SpecialCheckpointUnsupported:
                    return "EidolonText092";
                case StudioMessageCode.ModelTensorsMissing:
                    return "EidolonText093";
                case StudioMessageCode.InvalidLoraWeights:
                    return "EidolonText094";
                case StudioMessageCode.InvalidCheckpointWeights:
                    return "EidolonText095";
                case StudioMessageCode.RefinerUnsupported:
                    return "EidolonText096";
                case StudioMessageCode.UnsupportedWeightsFamily:
                    return "EidolonText097";
                case StudioMessageCode.EmptyJsonDocument:
                    return "EidolonText098";
                case StudioMessageCode.JsonReadFailed:
                    return "EidolonText099";
                case StudioMessageCode.InvalidJobId:
                    return "EidolonText101";
                case StudioMessageCode.UnsupportedJobSchema:
                    return "EidolonText102";
                case StudioMessageCode.InvalidJobDirectory:
                    return "EidolonText103";
                case StudioMessageCode.JobInterrupted:
                    return "EidolonText104";
                case StudioMessageCode.InvalidJobImagePath:
                    return "EidolonText105";
                case StudioMessageCode.InvalidServerAddress:
                    return "EidolonText254";
                case StudioMessageCode.ServerConnecting:
                    return "EidolonText255";
                case StudioMessageCode.ServerConnected:
                    return "EidolonText256";
                case StudioMessageCode.ExternalCancellationFailed:
                    return "EidolonText257";
                case StudioMessageCode.ExternalAssetImportUnsupported:
                    return "EidolonText258";
                case StudioMessageCode.LocalTrainingRuntimeRequired:
                    return "EidolonText261";
                case StudioMessageCode.InvalidReferenceImage:
                    return "EidolonText450";
                case StudioMessageCode.InvalidReferenceOptions:
                    return "EidolonText451";
                case StudioMessageCode.PreparingReferenceImage:
                    return "EidolonText452";
                case StudioMessageCode.ReferenceImageUploading:
                    return "EidolonText453";
                default:
                    throw new ArgumentOutOfRangeException(nameof(code), code, null);
            }
        }
    }
}
